version: "3.9"
services: 
  php: 
    build:   
      context: ./
      dockerfile: Dockerfile
    container_name: laravelsup-server
    restart: always
    ports: 
      - 5001:80
  mariadb:
    image: "mariadb:10.5.9"
    ports:
      - "4407:3306"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "Facturacion"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    volumes:
      - ./sql:/Facturacionb.d    
    